baseURL: "https://ruiagmsousa.github.io" 
title: Rui Sousa
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Curriculum
          url: curriculum/
          weight: 3
        
params:
    description: "I am a $4^{th}$ year economics PhD student at Northwestern University."
    author: Rui Sousa
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers", "Curriculum"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Rui Sousa
          subtitle: "Hi there! I am a 4$^{th}$ year PhD student at the economics department of Northwestern University. I am a macroeconomist interested in the energy transition, shock propagation and financial frictions. \n\n Previously, I worked as a Research Assistant at the Centre for Macroeconomics at the LSE under professors Benjamin Moll and Ricardo Reis. Before academia I worked as an analyst and trainee at the European Central Bank. \n\n I obtained my BSc from the University of Porto and MSc from Nova School of Business and Economics in Portugal."  
          imageUrl: "profile_photo.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Curriculum
              url: curriculum/
            
    socialIcons:
        - name: CV
          url: cv/cv.pdf
        - name: Email
          url: mailto:rui.agm.sousa@u.northwestern.edu
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/ruiagmsousa
        
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rui Sousa"
      icon: favicon/favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2